// Generated by CoffeeScript 1.8.0
(function() {
  var CompositeDisposable, HackUtils, HackUtilsView;

  HackUtilsView = require('./hack-utils-view');

  CompositeDisposable = require('atom').CompositeDisposable;

  console.log(module.paths);

  module.require('/home/romgrk/github/hack-utils/lib/hack-utils.coffee');

  module.exports = HackUtils = {
    Config: {
      set: 'ok'
    },
    hackUtilsView: null,
    modalPanel: null,
    subscriptions: null,
    activate: function(state) {
      this.hackUtilsView = new HackUtilsView(state.hackUtilsViewState);
      this.subscriptions = new CompositeDisposable;
      return this.subscriptions.add(atom.commands.add('atom-workspace', {
        'hack-utils:toggle': (function(_this) {
          return function() {
            return _this.toggle();
          };
        })(this)
      }));
    },
    deactivate: function() {
      this.modalPanel.destroy();
      this.subscriptions.dispose();
      return this.hackUtilsView.destroy();
    },
    serialize: function() {
      return {
        hackUtilsViewState: this.hackUtilsView.serialize()
      };
    },
    toggle: function() {
      console.log('HackUtils was toggled!');
      if (this.modalPanel.isVisible()) {
        return this.modalPanel.hide();
      } else {
        return this.modalPanel.show();
      }
    }
  };

}).call(this);
